# -*- coding: utf-8 -*-
"""malltrendAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXWjtByQcfiiER1BTGWuG8i5kg9UUqnW
"""

import json
import pandas as pd
from google import genai
import feedparser
import os

from dotenv import load_dotenv
load_dotenv()

api_key=os.getenv('mall_trend_api')
youtube_api = os.getenv('youtube_api')
news_api = os.getenv('news_api')

import requests

YOUTUBE_API_KEY = youtube_api

def collect_youtube_trends(keyword, max_results=10):
    url = "https://www.googleapis.com/youtube/v3/search"

    params = {
        "part": "snippet",
        "q": keyword,
        "type": "video",
        "order": "date",
        "maxResults": max_results,
        "key": YOUTUBE_API_KEY
    }

    data = requests.get(url, params=params).json()

    videos = []
    for item in data.get("items", []):
        videos.append({
            "source": "YouTube",
            "title": item["snippet"]["title"],
            "text": item["snippet"]["description"],
            "url": "https://www.youtube.com/watch?v=" + item["id"]["videoId"]
        })
    return videos

NEWS_API_KEY = news_api

def collect_news_trends(keyword, limit=10):
    url = "https://newsapi.org/v2/everything"

    params = {
        "q": keyword,
        "language": "en",
        "sortBy": "publishedAt",
        "pageSize": limit,
        "apiKey": NEWS_API_KEY
    }

    data = requests.get(url, params=params).json()

    articles = []
    for article in data.get("articles", []):
        articles.append({
            "source": article["source"]["name"],
            "title": article["title"],
            "text": article["description"],
            "url": article["url"]
        })
    return articles

def collect_rss_trends(rss_url="https://www.retaildive.com/feeds/news/", limit=10):
    feed = feedparser.parse(rss_url)

    items = []
    for entry in feed.entries[:limit]:
        items.append({
            "source": "RSS",
            "title": entry.get("title", ""),
            "text": entry.get("summary", ""),
            "url": entry.get("link", "")
        })
    return items

def collect_all_trends(category_keyword):
    all_data = []

    try:
        all_data += collect_youtube_trends(category_keyword)
    except Exception as e:
        print("YouTube error:", e)

    try:
        all_data += collect_news_trends(category_keyword)
    except Exception as e:
        print("News error:", e)

    try:
        all_data += collect_rss_trends()
    except Exception as e:
        print("RSS error:", e)

    return all_data

def format_trend_data(data):
    text = ""
    for item in data:
        text += f"""
Source: {item['source']}
Title: {item['title']}
Details: {item['text']}
URL: {item['url']}
"""
    return text

import json
from google import genai

client = genai.Client(api_key=api_key)

def analyze_mall_trends(category, city):
    collected_data = collect_all_trends(category)
    formatted_data = format_trend_data(collected_data)

    prompt = f"""
You are MallTrend AI, an AI decision intelligence agent for mall businesses.

City: {city}
Shop Category: {category}

Trend Data:
{formatted_data}

Your primary goal is to provide insights and recommendations *strictly* for the provided '{category}' shop category.

Return a practical business report in this exact JSON format:

{{
  "overallTrendScore": 0,
  "confidenceLevel": 0,
  "predictedDemand": "Low / Medium / High",
  "trendingItems": [
    {{
      "rank": 1,
      "item": "Item name",
      "trendScore": 0,
      "reason": "Why it is trending",
      "targetCustomers": "Target audience"
    }}
  ],
  "recommendations": {{
    "stocking": "What to stock, *specifically for {category}*",
    "marketing": "Marketing idea, *specifically for {category}*",
    "bestTimeToPromote": "Best time, *specifically for {category}*",
    "riskLevel": "Low / Medium / High"
  }},
  "finalActionPlan": [
    "Action 1 (related to {category})",
    "Action 2 (related to {category})",
    "Action 3 (related to {category})"
  ]
}}

Rules:
- Ensure all 'trendingItems', 'recommendations', and 'finalActionPlan' are strictly relevant to the 'Shop Category' provided. Do not include items or recommendations for other categories.
- If specific trending items are hard to pinpoint for a broad category, provide a general trend and inferred recommendations, ensuring all fields in the JSON are populated with the best available information, or a note about data limitations if truly no specific detail can be inferred.
- Only return valid JSON.
"""

    response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt,
    config={
        "temperature":0.3
    }
)

    text = response.text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "").replace("```", "").strip()
    elif text.startswith("```"):
        text = text.replace("```", "").strip()

    return json.loads(text)

def category_analyzer_agent(city, formatted_data):
    prompt = f"""
You are MallTrend AI's Category Analyzer Agent.

City: {city}

Raw Trend Data:
{formatted_data}

Your task:
Classify the trends into mall shop categories.

Return only valid JSON in this exact format:

{{
  "city": "{city}",
  "detected_categories": [
    {{
      "category": "Food Court",
      "trend_signals": ["signal 1", "signal 2"],
      "top_keywords": ["keyword 1", "keyword 2"],
      "customer_segment": "Who is interested",
      "category_strength": 0
    }},
    {{
      "category": "Fashion & Apparel",
      "trend_signals": ["signal 1", "signal 2"],
      "top_keywords": ["keyword 1", "keyword 2"],
      "customer_segment": "Who is interested",
      "category_strength": 0
    }},
    {{
      "category": "Cosmetics & Beauty",
      "trend_signals": ["signal 1", "signal 2"],
      "top_keywords": ["keyword 1", "keyword 2"],
      "customer_segment": "Who is interested",
      "category_strength": 0
    }},
    {{
      "category": "Toys & Games",
      "trend_signals": ["signal 1", "signal 2"],
      "top_keywords": ["keyword 1", "keyword 2"],
      "customer_segment": "Who is interested",
      "category_strength": 0
    }}
  ],
  "highest_opportunity_category": "Category name",
  "summary": "Short business summary"
}}

Rules:
- category_strength must be between 0 and 100.
- If a category has no strong signals, still include it with lower score.
- Keep output useful for mall shop owners.
- Only return valid JSON.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    text = response.text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "").replace("```", "").strip()
    elif text.startswith("```"):
        text = text.replace("```", "").strip()

    return json.loads(text)

def demand_prediction_agent(city, category_analysis):
    prompt = f"""
You are MallTrend AI's Demand Prediction Agent.

City: {city}

Category Analysis Data:
{json.dumps(category_analysis, indent=2)}

Your task:
Predict mall demand for each category based on:
- trend strength
- customer segment
- category opportunity
- seasonality
- social media interest
- business risk

Return only valid JSON in this exact format:

{{
  "city": "{city}",
  "demand_predictions": [
    {{
      "category": "Food Court",
      "demand_score": 0,
      "predicted_demand": "Low / Medium / High",
      "sales_opportunity": "Short explanation",
      "best_items_to_promote": ["item 1", "item 2", "item 3"],
      "peak_customer_time": "Best time",
      "risk_level": "Low / Medium / High",
      "reason": "Why this demand is predicted"
    }}
  ],
  "best_category_to_focus": "Category name",
  "overall_mall_opportunity_score": 0,
  "business_summary": "Short summary for mall manager"
}}

Rules:
- demand_score must be between 0 and 100.
- predicted_demand must be Low, Medium, or High.
- Include all categories found in the category analysis.
- Keep output practical for mall owners and shopkeepers.
- Only return valid JSON.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    text = response.text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "").replace("```", "").strip()
    elif text.startswith("```"):
        text = text.replace("```", "").strip()

    return json.loads(text)

def product_recommendation_agent(city, category_analysis):
    prompt = f"""
You are MallTrend AI's Product Recommendation Agent.

City: {city}

Category Analysis Data:
{json.dumps(category_analysis, indent=2)}

Your task:
Based on the category analysis data, identify and recommend specific products or product types that would be most popular or have high demand within each detected category.

Return only valid JSON in this exact format:

{{
  "city": "{city}",
  "recommended_products_by_category": [
    {{
      "category": "Food Court",
      "recommended_products": [
        {{
          "product_name": "Gourmet Burgers",
          "reason": "High social media interest in unique food experiences."
        }},
        {{
          "product_name": "Bubble Tea Bar",
          "reason": "Consistent trend signals for specialty beverages and customization."
        }}
      ]
    }},
    {{
      "category": "Fashion & Apparel",
      "recommended_products": [
        {{
          "product_name": "Sustainable Athleisure Wear",
          "reason": "Growing customer segment interested in eco-friendly and comfortable fashion."
        }},
        {{
          "product_name": "Personalized Denim Jackets",
          "reason": "Top keywords indicate a desire for unique, customizable apparel."
        }}
      ]
    }}
  ],
  "overall_recommendation_summary": "A brief summary of the top product opportunities across all categories."
}}

Rules:
- For each category in 'detected_categories', provide at least 2-3 specific product recommendations.
- The recommendations should be practical and actionable for mall shop owners.
- Base recommendations on 'trend_signals', 'top_keywords', and 'customer_segment' from the category analysis.
- Only return valid JSON.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={
            "temperature":0.3
        }
    )

    text = response.text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "").replace("```", "").strip()
    elif text.startswith("```"):
        text = text.replace("```", "").strip()

    return json.loads(text)

def compare_trends_agent(city: str, trend1_name: str, trend2_name: str):
    prompt = f"""
You are MallTrend AI's Comparative Trends Agent.

City: {city}
Your task:
Compare two trending values: '{trend1_name}' and '{trend2_name}'.
Analyze their potential for profit and suggest which one the owner should invest in, providing reasons for your recommendation.
If detailed trend data is not available, provide a mock comparison based on general market understanding for these types of items.

Return only valid JSON in this exact format:

{{
  "city": "{city}",
  "trend1_name": "{trend1_name}",
  "trend2_name": "{trend2_name}",
  "comparison_summary": "A summary of the comparison between '{trend1_name}' and '{trend2_name}'.",
  "key_metrics_comparison": [
    {{
      "metric": "Trend Score",
      "trend1_value": 75,
      "trend2_value": 60,
      "notes": "Relative trend strength."
    }},
    {{
      "metric": "Predicted Demand",
      "trend1_value": "High",
      "trend2_value": "Medium",
      "notes": "Expected demand for each trend."
    }}
  ],
  "investment_suggestion": {{
    "invest_in": "Either '{trend1_name}', '{trend2_name}', or 'Neither' or 'Both'",
    "reason": "Detailed reasons why investing in the suggested trend(s) would yield more profit, considering aspects like market growth, customer interest, and potential for longevity. If neither, explain why."
  }},
  "future_enhancement_note": "For a true comparative analysis, the system would need real-time data for both specific trends to provide more accurate insights."
}}

Rules:
- The JSON must be valid.
- The content should be relevant to the provided trends, even if it's a simulated comparison.
- The `future_enhancement_note` should always be included.
- Be decisive in the 'invest_in' field if one is clearly better.
"""
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={
            "temperature":0.5 # A bit higher temperature for more creative comparison
        }
    )

    text = response.text.strip()

    if text.startswith("```json"):
        text = text.replace("```json", "").replace("```", "").strip()
    elif text.startswith("```"):
        text = text.replace("```", "").strip()

    return json.loads(text)

def mall_trend_assistant_agent(city: str, category: str, user_query: str, all_agent_outputs: dict):
    prompt = f"""
You are MallTrendAssistant, an AI designed to assist mall business owners with insights derived from detailed trend analysis reports.

Here are the latest trend analysis reports for {category} in {city}:

Overall Mall Trends Report:
{json.dumps(all_agent_outputs.get('overall_mall_trends_report', {}), indent=2)}

Category Analysis Report:
{json.dumps(all_agent_outputs.get('category_analysis_report', {}), indent=2)}

Demand Prediction Report:
{json.dumps(all_agent_outputs.get('demand_prediction_report', {}), indent=2)}

Product Recommendation Report:
{json.dumps(all_agent_outputs.get('product_recommendation_report', {}), indent=2)}

Comparative Trends Report:
{json.dumps(all_agent_outputs.get('comparison_report_json', {}), indent=2)}


Based on these reports, please answer the following question from a mall business owner:
{user_query}

Provide a concise and helpful answer, drawing directly from the provided analysis. If the information isn't directly available in the reports, state that politely.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash", # Using a fast model for conversational purposes
        contents=prompt,
        config={
            "temperature": 0.7 # A bit higher temperature for more conversational responses
        }
    )

    return response.text.strip()

def run_all_agents_with_raw_json(city: str, category_keyword: str, trend1_name: str, trend2_name: str):


    def to_json_string(data):
        if isinstance(data, dict):
            return json.dumps(data, indent=2)
        return str(data)

    overall_mall_trends_report = {"error": "No data available yet."} # Initialize as dict
    category_analysis_report = {"error": "No data available yet."} # Initialize as dict
    demand_prediction_report = {"error": "No data available yet."} # Initialize as dict
    product_recommendation_report = {"error": "No data available yet."} # Initialize as dict
    comparison_report_json = {"error": "No comparison data available yet."} # Initialize as dict
    raw_trend_data_for_agents = []
    raw_data_source_count = 0

    try:
        raw_trend_data_for_agents = collect_all_trends(category_keyword)
        raw_data_source_count = len(raw_trend_data_for_agents)
        formatted_trend_data_for_agents = format_trend_data(raw_trend_data_for_agents)

        if not formatted_trend_data_for_agents.strip():
            error_message = f"No trend data found for category '{category_keyword}'. Please try a different keyword or check API limits."
            return (
                to_json_string({"error": error_message}),
                to_json_string({"error": error_message}),
                to_json_string({"error": error_message}),
                to_json_string({"error": error_message}),
                to_json_string({"error": error_message}),
                raw_data_source_count
            )

    except Exception as e:
        formatted_trend_data_for_agents = f"Error collecting or formatting trend data: {e}"
        return (
            to_json_string({"error": formatted_trend_data_for_agents}),
            to_json_string({"error": formatted_trend_data_for_agents}),
            to_json_string({"error": formatted_trend_data_for_agents}),
            to_json_string({"error": formatted_trend_data_for_agents}),
            to_json_string({"error": formatted_trend_data_for_agents}),
            raw_data_source_count
        )

    try:
        overall_mall_trends_report = analyze_mall_trends(category_keyword, city)
    except Exception as e:
        overall_mall_trends_report = {"error": f"Error calling analyze_mall_trends: {e}"}

    try:
        category_analysis_report = category_analyzer_agent(city, formatted_trend_data_for_agents)
    except Exception as e:
        category_analysis_report = {"error": f"Error calling category_analyzer_agent: {e}"}

    if isinstance(category_analysis_report, dict) and "error" not in category_analysis_report:
        try:
            demand_prediction_report = demand_prediction_agent(city, category_analysis_report)
        except Exception as e:
            demand_prediction_report = {"error": f"Error calling demand_prediction_agent: {e}"}
    else:
        demand_prediction_report = {"error": "Skipped: Category Analysis had an error or was not available."}

    if isinstance(category_analysis_report, dict) and "error" not in category_analysis_report:
        try:
            product_recommendation_report = product_recommendation_agent(city, category_analysis_report)
        except Exception as e:
            product_recommendation_report = {"error": f"Error calling product_recommendation_agent: {e}"}
    else:
        product_recommendation_report = {"error": "Skipped: Category Analysis had an error or was not available."}

    try:
        comparison_report_json = compare_trends_agent(city, trend1_name, trend2_name)
    except Exception as e:
        comparison_report_json = {"error": f"Error calling compare_trends_agent: {e}"}

    return (
        to_json_string(overall_mall_trends_report),
        to_json_string(category_analysis_report),
        to_json_string(demand_prediction_report),
        to_json_string(product_recommendation_report),
        to_json_string(comparison_report_json),
        raw_data_source_count
    )

import gradio as gr
import json
import feedparser
import html

# Main function to run all agents and prepare outputs for Gradio
def run_all_agents(city: str, category_keyword: str, trend1_name: str, trend2_name: str):
    overall_mall_trends_report = None
    category_analysis_report = None
    demand_prediction_report = None
    product_recommendation_report = None
    comparison_report_json = json.dumps({"error": "No comparison data available yet."})
    raw_trend_data_for_agents = []  # Initialize as empty list
    raw_data_source_count = 0  # Initialize count

    # --- Step 1: Collect and format raw trend data (for Category Analysis, Demand Prediction, Product Recommendation) ---
    try:
        raw_trend_data_for_agents = collect_all_trends(category_keyword)
        raw_data_source_count = len(raw_trend_data_for_agents)
        formatted_trend_data_for_agents = format_trend_data(raw_trend_data_for_agents)

        if not formatted_trend_data_for_agents.strip():  # Check if it's empty or just whitespace
            error_message = f"No trend data found for category '{category_keyword}'. Please try a different keyword or check API limits."
            print(error_message)
            return (
                json.dumps({"error": error_message}),
                json.dumps({"error": error_message}),
                json.dumps({"error": error_message}),
                json.dumps({"error": error_message}),
                json.dumps({"error": error_message}), # New return for comparison_report_json
                raw_data_source_count  # Include count even if no data
            )

    except Exception as e:
        formatted_trend_data_for_agents = f"Error collecting or formatting trend data: {e}"
        print(formatted_trend_data_for_agents)
        # Return errors for all outputs if data collection fails
        return (
            json.dumps({"error": formatted_trend_data_for_agents}),
            json.dumps({"error": formatted_trend_data_for_agents}),
            json.dumps({"error": formatted_trend_data_for_agents}),
            json.dumps({"error": formatted_trend_data_for_agents}),
            json.dumps({"error": formatted_trend_data_for_agents}), # New return for comparison_report_json
            raw_data_source_count  # Will be 0 in case of collection error
        )

    # --- Step 2: Call analyze_mall_trends agent ---
    try:
        overall_mall_trends_report = analyze_mall_trends(category_keyword, city)
    except Exception as e:
        overall_mall_trends_report = json.dumps({"error": f"Error calling analyze_mall_trends: {e}"})
        print(overall_mall_trends_report)

    # --- Step 3: Call category_analyzer_agent ---
    try:
        category_analysis_report = category_analyzer_agent(city, formatted_trend_data_for_agents)
    except Exception as e:
        category_analysis_report = json.dumps({"error": f"Error calling category_analyzer_agent: {e}"})
        print(category_analysis_report)

    # --- Step 4: Call demand_prediction_agent (depends on category_analysis_report) ---
    if isinstance(category_analysis_report, dict):
        try:
            demand_prediction_report = demand_prediction_agent(city, category_analysis_report)
        except Exception as e:
            demand_prediction_report = json.dumps({"error": f"Error calling demand_prediction_agent: {e}"})
            print(demand_prediction_report)
    else:
        demand_prediction_report = json.dumps({"error": "Skipped: Category Analysis had an error or was not available."})

    # --- Step 5: Call product_recommendation_agent (depends on category_analysis_report) ---
    if isinstance(category_analysis_report, dict):
        try:
            product_recommendation_report = product_recommendation_agent(city, category_analysis_report)
        except Exception as e:
            product_recommendation_report = json.dumps({"error": f"Error calling product_recommendation_agent: {e}"})
            print(product_recommendation_report)
    else:
        product_recommendation_report = json.dumps({"error": "Skipped: Category Analysis had an error or was not available."})

    # --- Step 6: Call compare_trends_agent ---
    try:
        comparison_report_json = compare_trends_agent(city, trend1_name, trend2_name)
    except Exception as e:
        comparison_report_json = json.dumps({"error": f"Error calling compare_trends_agent: {e}"})
        print(comparison_report_json)

    # Convert dicts to pretty-printed JSON strings for display in Gradio Textboxes/JSON components
    def to_json_string(data):
        if isinstance(data, dict):
            return json.dumps(data, indent=2)
        return str(data)

    # Return as separate arguments matching the Gradio outputs
    return (
        to_json_string(overall_mall_trends_report),
        to_json_string(category_analysis_report),
        to_json_string(demand_prediction_report),
        to_json_string(product_recommendation_report),
        to_json_string(comparison_report_json), # New return value
        raw_data_source_count  # Return the count of collected data sources
    )

def render_main_content(city, category, view_type, trend1_name="", trend2_name=""):
    # Initialize variables to ensure they always have a value
    overall_json = json.dumps({"error": "No data available yet."})
    category_report_json = json.dumps({"error": "No data available yet."})
    demand_json = json.dumps({"error": "No data available yet."})
    products_json = json.dumps({"error": "No data available yet."})
    comparison_json = json.dumps({"error": "No data available yet."})
    raw_data_count = 0

    # Call run_all_agents once to get all data
    overall_json, category_report_json, demand_json, products_json, comparison_json, raw_data_count = run_all_agents(city, category, trend1_name, trend2_name)

    def _parse_json_safely(json_string):
        try:
            return json.loads(json_string)
        except json.JSONDecodeError:
            return {"error": "Invalid JSON string received"}

    overall_data = _parse_json_safely(overall_json)
    category_report_data = _parse_json_safely(category_report_json)
    demand_data = _parse_json_safely(demand_json)
    products_data = _parse_json_safely(products_json)
    comparison_data = _parse_json_safely(comparison_json)

    main_content_html = ""

    if view_type == 'dashboard':

        overall_trend_score = html.escape(str(overall_data.get("overallTrendScore", "N/A")))
        confidence_level = html.escape(str(overall_data.get("confidenceLevel", "N/A")))
        predicted_demand = html.escape(str(overall_data.get("predictedDemand", "N/A")))
        trending_items = overall_data.get("trendingItems", [])[:5] # Limit to 5 items
        rising_products_found = len(trending_items)

        recommendations = overall_data.get("recommendations", {})
        stocking_rec = html.escape(recommendations.get("stocking", "N/A"))
        marketing_rec = html.escape(recommendations.get("marketing", "N/A"))
        best_time_to_promote_rec = html.escape(recommendations.get("bestTimeToPromote", "N/A"))
        rec_confidence = html.escape(str(overall_data.get("confidenceLevel", "N/A")))  # Using overall confidence for now

        final_action_plan = overall_data.get("finalActionPlan", [])[:5] # Limit to 5 items

        trending_items_html = ""
        if trending_items:
            for item in trending_items:
                trending_items_html += f"""
              <tr>
                <td>{html.escape(str(item.get("rank", "N/A")))}</td>
                <td>{html.escape(item.get("item", "N/A"))}</td>
                <td>{html.escape(item.get("reason", "N/A"))}</td>
                <td>{html.escape(str(item.get("trendScore", "N/A")))}/100</td>
              </tr>
            """
        else:
            trending_items_html = "<tr><td colspan='4'>No trending items found.</td></tr>"

        final_action_plan_html = ""
        if final_action_plan:
            for action in final_action_plan:
                final_action_plan_html += f"<li>{html.escape(action)}</li>\n"
        else:
            final_action_plan_html = "<li>No action plan provided.</li>\n"

        main_content_html = f"""
        <div class=\"header\">
          <div>
            <h1>AI Trend Analysis Report</h1>
            <p>Category: {html.escape(category)} \u2022 Location: {html.escape(city)}</p>
          </div>
          <button>+ New Analysis</button>
        </div>

        <div class=\"cards\">
          <div class=\"card\">
            <p>Overall Trend Score</p>
            <h2>{overall_trend_score}/100</h2>
            <span>{predicted_demand}</span>
          </div>
          <div class=\"card\">
            <p>Rising Products Found</p>
            <h2>{rising_products_found}</h2>
            <span>High Potential Items</span>
          </div>
          <div class=\"card\">
            <p>Data Sources Analyzed</p>
            <h2>{raw_data_count}</h2>
            <span>Social, News & Search</span>
          </div>
          <div class=\"card\">
            <p>Confidence Level</p>
            <h2>{confidence_level}%</h2>
            <span>Highly Reliable</span>
          </div>
          <div class=\"card\">
            <p>Predicted Demand</p>
            <h2>{predicted_demand}</h2>
            <span>Next 2\u20134 Weeks</span>
          </div>
        </div>

        <div class=\"grid\">
          <section class=\"panel large\">
            <h2 class=\"colo\">\U0001F525 Top Trending Items for {html.escape(category)}</h2>
            <table>
              <tr>
                <th>Rank</th>
                <th>Item</th>
                <th>Why It's Trending</th>
                <th>Demand</th>
              </tr>
              {trending_items_html}
            </table>
          </section>

          <section class=\"panel\">
            <h2 class=\"colo\">\U0001F916 AI Agent Recommendations</h2>
            <div class=\"rec colo\">\U0001F4E6 <b class=\"colo\">Stocking:</b> {stocking_rec}</div>
            <div class=\"rec\">\U0001F4E3 <b class=\"colo\">Marketing:</b> {marketing_rec}</div>
            <div class=\"rec\">\u23f0 <b class=\"colo\">Best Time:</b> {best_time_to_promote_rec}</div>
            <div class=\"meter\">{rec_confidence}%<br><small class=\"colo\">Highly Reliable</small></div>
          </section>
        </div>

        <div class=\"grid bottom\">

          <section class=\"panel\">
            <h2 class=\"colo\">\U0001F310 Top Data Sources</h2>
            <ul class=\"colo\">
              <li>Instagram Reels</li>
              <li>YouTube Shorts</li>
              <li>News & Blogs</li>
            </ul>
          </section>

          <section class=\"panel\">
            <h2 class=\"colo\">\u2705 Final Action Plan</h2>
            <ul>
              {final_action_plan_html}
            </ul>
          </section>
        </div>

        <div class=\"insight\">
          \u2728 MallTrend AI Insight: Trends are based on real-time analysis from multiple online sources.
        </div>
        """

    elif view_type == 'category_insights':
        category_data = _parse_json_safely(category_report_json)

        category_cards = ""
        for item in category_data.get("detected_categories", []):
            category_cards += f"""
            <div class=\"card\">
              <p>{html.escape(item.get("category", "N/A"))}</p>
              <h2>{html.escape(str(item.get("category_strength", "N/A")))}/100</h2>
              <span>{html.escape(item.get("customer_segment", "N/A"))}</span>
            </div>
            """

        main_content_html = f"""
        <div class=\"header\">
          <div>
            <h1>\U0001F4DA Category Insights Report</h1>
            <p>Category: {html.escape(category)} \u2022 Location: {html.escape(city)}</p>
          </div>
        </div>

        <div class=\"cards\">
          {category_cards}
        </div>

        <section class=\"panel large\">
          <h2 class=\"colo\">Highest Opportunity</h2>
          <p>{html.escape(category_data.get("highest_opportunity_category", "N/A"))}</p>
          <p>{html.escape(category_data.get("summary", "No summary available."))}</p>
        </section>
        """

    elif view_type == 'comparative_trends':
        comp_summary = html.escape(comparison_data.get("comparison_summary", "N/A"))
        future_note = html.escape(comparison_data.get("future_enhancement_note", "N/A"))
        trend1_name_display = html.escape(comparison_data.get("trend1_name", "N/A"))
        trend2_name_display = html.escape(comparison_data.get("trend2_name", "N/A"))
        investment_suggestion_text = html.escape(comparison_data.get("investment_suggestion", {}).get("invest_in", "N/A"))
        investment_suggestion_reason = html.escape(comparison_data.get("investment_suggestion", {}).get("reason", "N/A"))

        metrics_html = ""
        for metric in comparison_data.get("key_metrics_comparison", []):
            metrics_html += f"""
            <li><b>{html.escape(metric.get("metric", "N/A"))}:</b>
                '{trend1_name_display}' Value - {html.escape(str(metric.get("trend1_value", "N/A")))},
                '{trend2_name_display}' Value - {html.escape(str(metric.get("trend2_value", "N/A")))}.
                Notes: {html.escape(metric.get("notes", ""))}
            </li>
            """
        if not metrics_html:
            metrics_html = "<li>No key metrics for comparison.</li>"

        main_content_html = f"""
        <div class=\"header\">
          <div>
            <h1>\U0001F4C9 Comparative Trends Report</h1>
            <p>Comparing: {trend1_name_display} vs. {trend2_name_display} \u2022 Location: {html.escape(city)}</p>
          </div>
          <button>+ New Analysis</button>
        </div>
        <section class=\"panel large\">
            <h2 class=\"colo\">Comparison Summary:</h2>
            <p>{comp_summary}</p>
            <h3 class=\"colo\">Key Metrics Comparison:</h3>
            <ul>
                {metrics_html}
            </ul>
            <h3 class=\"colo\">Investment Suggestion:</h3>
            <p><b>Invest in:</b> {investment_suggestion_text}</p>
            <p><b>Reason:</b> {investment_suggestion_reason}</p>
            <h3 class=\"colo\">Note on Future Enhancements:</h3>
            <p>{future_note}</p>
            <h3 class=\"colo\">Raw Comparison Data (JSON):</h3>
            <pre>{html.escape(comparison_json)}</pre>
        </section>
        """
    return f"""
    <main class=\"content\">
        {main_content_html}
    </main>
    """

css = """
html,
body,
.gradio-container {
    background: linear-gradient(135deg, #749dd6, #102a99) !important;
    color: #f8fafc !important;
    min-height: 100vh;
}

.gradio-container {
    max-width: 100% !important;
    padding: 0 !important;
}

.dashboard {
    background: transparent !important;
    min-height: 100vh;
}

.content {
    background: rgba(255,255,255,0.06) !important;
    backdrop-filter: blur(20px);
}

.block,
.gr-block,
.gr-box,
.gr-form {
    background: transparent !important;
}

.dashboard {
  display: flex;
  min-height: 100vh;
  font-family: Inter, Arial, sans-serif;
}

.sidebar {
  width: 300px;
  background: rgba(8, 27, 80, 0.95);
  color: #f8fafc;
  padding: 30px 22px;
  border-right: 1px solid rgba(255,255,255,0.08);
}

.sidebar h1 {
  font-size: 28px;
  margin-bottom: 8px;
}

.sidebar p {
  color: rgba(248,250,252,0.75);
  margin-bottom: 24px;
  line-height: 1.6;
}

.auth-panel {
  margin: 20px 0 28px;
  padding: 18px;
  border-radius: 20px;
  background: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.12);
}

.auth-panel h2 {
  margin-top: 0;
  font-size: 18px;
  color: #dbeafe;
}

.auth-panel .input-field {
  width: 100%;
  margin: 10px 0;
  padding: 12px 14px;
  border-radius: 14px;
  border: 1px solid rgba(255,255,255,0.15);
  background: rgba(255,255,255,0.08);
  color: #f8fafc;
}

.auth-panel .auth-buttons {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}

.auth-panel .auth-button {
  flex: 1;
  min-width: 120px;
  border: none;
  border-radius: 14px;
  padding: 12px 14px;
  color: white;
  font-weight: 700;
  cursor: pointer;
  background: linear-gradient(90deg, #4f7cff, #3a63df);
}

.auth-panel .auth-button.logout {
  background: rgba(255,255,255,0.12);
}

.auth-panel #firebase-status {
  margin-top: 12px;
  color: #a5b4fc;
  font-size: 14px;
}

.menu {
  padding: 14px 16px;
  border-radius: 16px;
  margin-bottom: 12px;
  font-weight: 700;
  color: #f8fafc;
  border: 1px solid rgba(255,255,255,0.12);
}

.menu.active {
  background: linear-gradient(90deg, #2d6cff, #5b4ef7);
  border-color: transparent;
}

.colo{
 color: #a5b4fc;
}

.ask-box {
  margin-top: 60px;
  padding: 20px;
  border-radius: 18px;
  background: rgba(255,255,255,0.08);
}

.primary-button button,
.header button {
  background: linear-gradient(90deg, #5b7dff, #2d6cff);
  color: white !important;
  border: none;
  border-radius: 14px;
  padding: 14px 20px;
  font-weight: 700;
  width: auto !important;
  min-width: 150px;
  height: 48px;
  cursor: pointer;
  box-shadow: 0 18px 35px rgba(45,108,255,0.18);
}

.content {
  flex: 1;
  padding: 34px;
}

.dashboard,
.dashboard * {
  color: #f8fafc;
}

.sidebar,
.sidebar * {
  color: #f8fafc;
}

.card p,
.header p,
th {
  color: rgba(248,250,252,0.80) !important;
}

.card h2,
.panel h2 {
  color: #dbeafe !important;
}

td,
li,
.rec {
  color: rgba(248,250,252,0.92) !important;
}

td:last-child {
  color: #a5f3fc !important;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header h1 {
  margin: 0;
  font-size: 34px;
}

.header p {
  color: rgba(248,250,252,0.75);
}

.cards {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 18px;
  margin: 24px 0;
}

.card,
.panel {
  background: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 22px;
  padding: 26px;
  box-shadow: 0 24px 80px rgba(7, 22, 74, 0.12);
}

.card h2 {
  color: #eff6ff;
  font-size: 36px;
  margin: 8px 0;
}

.card span {
  color: #c7d2fe;
  font-weight: 700;
}

.card p {
  color: rgba(248,250,252,0.75);
  margin-bottom: 10px;
}

.panel{
  color: #f8fafc;
}

pre {
  background: rgba(15,23,42,0.9) !important;
  color: #e2e8f0 !important;
  padding: 20px;
  border-radius: 18px;
  overflow-x: auto;
  white-space: pre-wrap;
  font-size: 14px;
  line-height: 1.8;
}

pre * {
  color: #e2e8f0 !important;
}

.grid {
  display: grid;
  grid-template-columns: 1.2fr 0.95fr;
  gap: 22px;
  margin-bottom: 22px;
}

.bottom {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

table {
  width: 100%;
  border-collapse: collapse;
}

th {
  text-align: left;
  color: rgba(248,250,252,0.75);
  font-size: 14px;
  padding-bottom: 16px;
}

td {
  padding: 16px 10px;
  border-top: 1px solid rgba(255,255,255,0.08);
  font-weight: 600;
}

td:last-child {
  color: #8b5cf6;
}

.rec {
  margin: 18px 0;
  padding: 16px;
  border-radius: 16px;
  background: rgba(94, 138, 255, 0.12);
  color : #eff6ff;
}

.meter {
  margin-top: 24px;
  text-align: center;
  font-size: 34px;
  font-weight: 800;
  color: #eff6ff;
  padding: 25px;
  border-radius: 22px;
  background: linear-gradient(135deg, rgba(59,130,246,0.18), rgba(99,102,241,0.22));
}

.chart {
  height: 130px;
  font-size: 42px;
  color: #a5b4fc;
  display: flex;
  align-items: center;
}

.insight {
  background: rgba(107, 114, 255, 0.12);
  padding: 20px;
  border-radius: 20px;
  color: #c7d2fe;
  font-weight: 600;
}

.assistant-question-box,
.assistant-response-box {
  background-color: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 16px;
  padding: 18px;
  margin-bottom: 18px;
  color: #e2e8f0;
  line-height: 1.75;
}

.assistant-question-box p,
.assistant-response-box p {
  margin: 0;
  color: #e2e8f0 !important;
}

@media(max-width: 900px) {
  .dashboard {
    flex-direction: column;
  }

  .sidebar {
    width: auto;
  }

  .cards,
  .grid,
  .bottom {
    grid-template-columns: 1fr;
  }
}

.primary-button {
    flex: 0 0 auto !important;
}

.primary-button button {
    width: auto !important;
    min-width: 150px;
}

.login-container {
    height: 80vh;
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
    width: 100%;
}
.circle {
    position: absolute;
    width: 300px;
    height: 300px;
    border: 4px solid white;
    border-radius: 50%;
    z-index: 1;
    pointer-events: none;
}
.auth-panel-login {
    z-index: 2;
    background: rgba(255, 255, 255, 0.1);
    backdrop-filter: blur(15px);
    padding: 40px;
    border-radius: 24px;
    border: 1px solid rgba(255,255,255,0.2);
    display: flex;
    flex-direction: column;
    gap: 15px;
    width: 350px;
    box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
}
.auth-panel-login .input-field {
    padding: 14px;
    border-radius: 12px;
    border: 1px solid rgba(255,255,255,0.3);
    outline: none;
    background: rgba(255,255,255,0.1);
    color: white;
    font-size: 16px;
    width: 100%;
    box-sizing: border-box;
}
.auth-panel-login .input-field::placeholder {
    color: rgba(255,255,255,0.7);
}
.hidden-btn {
    display: none !important;
}
"""

# Override the original run_all_agents with the modified version
run_all_agents = run_all_agents_with_raw_json

firebase_script = """
<script type='module'>
    (async () => {
        try {
            const [firebaseAppModule, authModule, firestoreModule] = await Promise.all([
                import('https://www.gstatic.com/firebasejs/10.11.0/firebase-app.js'),
                import('https://www.gstatic.com/firebasejs/10.11.0/firebase-auth.js'),
                import('https://www.gstatic.com/firebasejs/10.11.0/firebase-firestore.js')
            ]);

            const { initializeApp: initApp } = firebaseAppModule;
            const { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } = authModule;
            const { getFirestore, collection, addDoc, serverTimestamp } = firestoreModule;

            const firebaseConfig = {
              apiKey: "AIzaSyDX2KYGrXGGn8iBFdgY3lcad99MLWr1TyQ",
              authDomain: "malltrendai.firebaseapp.com",
              projectId: "malltrendai",
              storageBucket: "malltrendai.firebasestorage.app",
              messagingSenderId: "719889768388",
              appId: "1:719889768388:web:41d6f11b37c55057318e91",
              measurementId: "G-H5LS3JTSN6"
            };

            const app = initApp(firebaseConfig);
            const auth = getAuth(app);
            const db = getFirestore(app);
            window.mallTrendFirebase = { auth, db };

            const statusEl = () => document.getElementById('firebase-status');
            const emailEl = () => document.getElementById('firebase-email');
            const passwordEl = () => document.getElementById('firebase-password');
            const dashboardBtn = () => document.getElementById('dashboard-btn');

            const updateStatus = (user) => {
                const status = statusEl();
                if (!status) return;
                if (user) {
                    status.textContent = 'Signed in as ' + user.email;
                    status.style.color = '#7dd3fc';
                } else {
                    status.textContent = 'Not signed in';
                    status.style.color = '#f8fafc';
                }
            };

            onAuthStateChanged(auth, (user) => { updateStatus(user); });

            window.firebaseLogin = async () => {
                try {
                    const email = emailEl().value;
                    const password = passwordEl().value;
                    if (!email || !password) {
                        alert('Please enter email and password.');
                        return;
                    }
                    await signInWithEmailAndPassword(auth, email, password);
                    updateStatus(auth.currentUser);
                    const dash = dashboardBtn();
                    if (dash) {
                        dash.click();
                    } else {
                        console.warn('Dashboard button not found.');
                    }
                    alert('Logged in as ' + email + '. Redirecting to dashboard...');
                } catch (error) {
                    console.error(error);
                    alert('Login failed: ' + error.message);
                }
            };

            window.firebaseLogout = async () => {
                try {
                    await signOut(auth);
                    updateStatus(null);
                    alert('Logged out successfully.');
                    location.reload();
                } catch (error) {
                    console.error(error);
                    alert('Logout failed: ' + error.message);
                }
            };

            window.saveMallTrendChat = async (chatData) => {
                try {
                    const user = auth.currentUser;
                    if (!user) {
                        console.warn('No authenticated Firebase user. Chat not saved.');
                        return;
                    }
                    await addDoc(collection(db, 'malltrendai_chats'), {
                        user_email: user.email,
                        city: chatData.city,
                        category: chatData.category,
                        user_question: chatData.question,
                        assistant_response: chatData.response,
                        createdAt: serverTimestamp(),
                        source: 'Gradio'
                    });
                    console.log('Chat saved to Firestore');
                } catch (error) {
                    console.error('Failed to save chat', error);
                }
            };
        } catch (error) {
            console.error('Firebase init failed', error);
        }
    })();
</script>
"""

with gr.Blocks(head=firebase_script, css=css) as dashboard:

    # State variable to keep track of the currently active view type
    current_view = gr.State('dashboard')

    with gr.Column(elem_id="login-screen") as login_screen:
        gr.HTML("""
        <div class="login-container">
            <div class="circle"></div>
            <div class='auth-panel-login'>
                <h1 style='color: white; margin-bottom: 20px; font-size: 28px; text-align: center; font-weight: bold;'>\U0001F916 MallTrend AI</h1>
                <input id='firebase-email' class='input-field' type='email' placeholder='Email' />
                <input id='firebase-password' class='input-field' type='password' placeholder='Password' />
                <div class='auth-buttons' style='display:flex; justify-content:center; width: 100%; margin-top: 15px;'>
                    <button class='auth-button' style='width: 100%; padding: 14px; border-radius: 12px; background: white; color: #102a99; font-size: 16px; font-weight: bold; border: none; cursor: pointer; box-shadow: 0 4px 15px rgba(0,0,0,0.2);' onclick='firebaseLogin()'>Login</button>
                </div>
                <div id='firebase-status' style='text-align: center; margin-top: 15px; color: #dbeafe;'>Not signed in</div>
            </div>
        </div>
        """)
        with gr.Group(elem_classes="hidden-btn"):
            login_success_btn = gr.Button("Login Success", elem_id="dashboard-btn")

    with gr.Row(visible=False, elem_id="main-app") as main_app:

        # Sidebar
        with gr.Column(scale=1):
            gr.Markdown("# \U0001F916 MallTrend AI")
            gr.Markdown("MallTrend AI helps mall businesses analyze trends, predict demand, and make data-driven decisions using real-time data and Generative AI.")
            gr.HTML("""
            <div class='auth-panel' style='background: transparent; border: none; padding: 0;'>
                <button class='auth-button logout' onclick='firebaseLogout()' style='width: 100%; background: rgba(255,255,255,0.12); color: white; border: none; padding: 12px; border-radius: 14px; cursor: pointer; font-weight: bold;'>Logout</button>
            </div>
            """)

            dashboard_btn = gr.Button("\U0001F4CA Dashboard")
            category_btn = gr.Button("\U0001F9E0 Category Insights")
            compare_btn = gr.Button("\U0001F4C9 Comparative Trends")
            assistant_btn = gr.Button("\U0001F916 MallTrend Assistant") # New button for the assistant

        # Main Content
        with gr.Column(scale=4):

            city = gr.Textbox(label="City", value="Hyderabad")
            category = gr.Textbox(label="Category", value="Trending Foods")

            # Group these two inputs for easier conditional visibility
            with gr.Row(visible=False) as comparative_trend_inputs_row:
                trend1_input = gr.Textbox(label="Trending Value 1 (for comparison)", value="Smartphones")
                trend2_input = gr.Textbox(label="Trending Value 2 (for comparison)", value="Smartwatches")

            # New input for the MallTrend Assistant
            with gr.Group(visible=False) as assistant_inputs_row:


              with gr.Row():
                  assistant_query = gr.Textbox(
                      label="Ask MallTrend Assistant",
                      placeholder="e.g., What are the best marketing strategies for 'Trending Foods'?",
                      scale=8
                  )

                  ask_assistant_btn = gr.Button(
                      "Ask Assistant",
                      scale=1,
                      min_width=150,
                      elem_classes="primary-button"
                  )

            generate_report_btn = gr.Button("Generate Report", elem_classes="primary-button")

            output = gr.HTML(value="<div style='padding: 20px; text-align: center; color: #a5b4fc; font-size: 1.2em;'>Select a view from the sidebar and click 'Generate Report' to see insights.</div>")


    # Helper function to decide which report to generate based on current_view state
    def _generate_report_from_inputs(city_val, category_val, t1_val, t2_val, assistant_query_val, current_view_state):
        if current_view_state == 'dashboard':
            return render_main_content(city_val, category_val, 'dashboard', "", "")
        elif current_view_state == 'category_insights':
            return render_main_content(city_val, category_val, 'category_insights', "", "")
        elif current_view_state == 'comparative_trends':
            return render_main_content(city_val, category_val, 'comparative_trends', t1_val, t2_val)
        elif current_view_state == 'assistant':
            # First, get all the raw data from agents
            overall_data, category_data, demand_data, products_data, comparison_data, _ = run_all_agents(city_val, category_val, t1_val, t2_val)

            all_agent_outputs = {
                'overall_mall_trends_report': overall_data,
                'category_analysis_report': category_data,
                'demand_prediction_report': demand_data,
                'product_recommendation_report': products_data,
                'comparison_report_json': comparison_data
            }
            assistant_response = mall_trend_assistant_agent(city_val, category_val, assistant_query_val, all_agent_outputs)
            chat_payload = json.dumps({
                "city": city_val,
                "category": category_val,
                "question": assistant_query_val,
                "response": assistant_response
            })
            return f"""
            <main class="content">
                <div class="header">
                    <div>
                        <h1>\U0001F916 MallTrend Assistant</h1>
                        <p>Ask me anything about {html.escape(category_val)} trends in {html.escape(city_val)}!</p>
                    </div>
                </div>
                <section class="panel large">
                    <h2 class="colo">Your Question:</h2>
                    <div class="assistant-question-box"><p>{html.escape(assistant_query_val)}</p></div>
                    <h2 class="colo">MallTrend Assistant's Response:</h2>
                    <div class="assistant-response-box"><p>{html.escape(assistant_response)}</p></div>
                </section>
            </main>
            <script>
              (async () => {{
                const chatData = JSON.parse({json.dumps(chat_payload)});
                if (window.saveMallTrendChat) {{
                  await window.saveMallTrendChat(chatData);
                }}
              }})();
            </script>
            """
        return "<div style='padding: 20px; text-align: center; color: #ff0000; font-size: 1.2em;'>Error: Unknown view type selected.</div>"

    # Event handlers for sidebar buttons
    dashboard_btn.click(
        lambda: ("<div style='padding: 20px; text-align: center; color: #5b21b6; font-size: 1.2em;'>Dashboard view selected. Click 'Generate Report'.</div>", gr.update(visible=False), gr.update(visible=False), gr.update(visible=True), 'dashboard'),
        inputs=[],
        outputs=[output, comparative_trend_inputs_row, assistant_inputs_row, generate_report_btn, current_view]
    )

    category_btn.click(
        lambda: ("<div style='padding: 20px; text-align: center; color: #5b21b6; font-size: 1.2em;'>Category Insights view selected. Click 'Generate Report'.</div>", gr.update(visible=False), gr.update(visible=False), gr.update(visible=True), 'category_insights'),
        inputs=[],
        outputs=[output, comparative_trend_inputs_row, assistant_inputs_row, generate_report_btn, current_view]
    )

    compare_btn.click(
        lambda: ("<div style='padding: 20px; text-align: center; color: #5b21b6; font-size: 1.2em;'>Comparative Trends view selected. Enter trend values and click 'Generate Report'.</div>", gr.update(visible=True), gr.update(visible=False), gr.update(visible=True), 'comparative_trends'),
        inputs=[],
        outputs=[output, comparative_trend_inputs_row, assistant_inputs_row, generate_report_btn, current_view]
    )

    assistant_btn.click(
        lambda: ("<div style='padding: 20px; text-align: center; color: #5b21b6; font-size: 1.2em;'>MallTrend Assistant selected. Enter your question and click 'Ask Assistant'.</div>", gr.update(visible=False), gr.update(visible=True), gr.update(visible=False), 'assistant'),
        inputs=[],
        outputs=[output, comparative_trend_inputs_row, assistant_inputs_row, generate_report_btn, current_view]
    )

    # Event handler for the Generate Report button (for Dashboard, Category, Comparative views)
    generate_report_btn.click(
        _generate_report_from_inputs,
        inputs=[city, category, trend1_input, trend2_input, assistant_query, current_view], # Pass assistant_query as well
        outputs=[output]
    )

    # Event handler for the 'Ask Assistant' button (only active when 'assistant' view is selected)
    ask_assistant_btn.click(
        _generate_report_from_inputs,
        inputs=[city, category, trend1_input, trend2_input, assistant_query, current_view], # Pass all relevant inputs
        outputs=[output]
    )

    login_success_btn.click(
        lambda: (gr.update(visible=False), gr.update(visible=True)),
        None,
        [login_screen, main_app]
    )

dashboard.launch(share=False, debug=True, css=css)

